"""add ontology core tables

Revision ID: 254675b4ef60
Revises: f7fdf44b4b65
Create Date: 2026-03-27 22:40:57.160901

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '254675b4ef60'
down_revision: Union[str, Sequence[str], None] = 'f7fdf44b4b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontology_object_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("parent_category IN ('Entity','Action','Concept','Attribute','Temporal')", name='ck_object_types_category'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_object_types_user_name')
    )
    op.create_index('idx_object_types_embedding', 'ontology_object_types', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_object_types_user', 'ontology_object_types', ['user_id', 'parent_category'], unique=False)
    op.create_table('ontology_action_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_type_id', sa.UUID(), nullable=True),
    sa.Column('param_schema', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('side_effects', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_type_id'], ['ontology_object_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_action_types_user_name')
    )
    op.create_index('idx_action_types_user', 'ontology_action_types', ['user_id'], unique=False)
    op.create_table('ontology_link_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type_id', sa.UUID(), nullable=True),
    sa.Column('target_type_id', sa.UUID(), nullable=True),
    sa.Column('cardinality', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cardinality IN ('1:1','1:N','N:M')", name='ck_link_types_cardinality'),
    sa.ForeignKeyConstraint(['source_type_id'], ['ontology_object_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_type_id'], ['ontology_object_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_link_types_user_name')
    )
    op.create_index('idx_link_types_user', 'ontology_link_types', ['user_id'], unique=False)
    op.create_table('ontology_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('chat','goal','habit','memory','knowledge','manual','llm_extracted')", name='ck_objects_source_type'),
    sa.CheckConstraint("status IN ('draft','verified','merged','archived')", name='ck_objects_status'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_objects_confidence'),
    sa.ForeignKeyConstraint(['type_id'], ['ontology_object_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_objects_embedding', 'ontology_objects', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_objects_source', 'ontology_objects', ['source_type', 'source_id'], unique=False)
    op.create_index('idx_objects_user_status', 'ontology_objects', ['user_id', 'status'], unique=False)
    op.create_index('idx_objects_user_type', 'ontology_objects', ['user_id', 'type_id'], unique=False)
    op.create_table('ontology_action_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_type_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('input_params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('affected_objects', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor IN ('user','agent','system','adapter')", name='ck_onto_action_logs_actor'),
    sa.CheckConstraint("status IN ('success','failed','rolled_back')", name='ck_onto_action_logs_status'),
    sa.ForeignKeyConstraint(['action_type_id'], ['ontology_action_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_onto_action_logs_type', 'ontology_action_logs', ['action_type_id'], unique=False)
    op.create_index('idx_onto_action_logs_user', 'ontology_action_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('ontology_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_origin', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_origin IN ('llm','system','manual')", name='ck_links_source_origin'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_links_confidence'),
    sa.CheckConstraint('source_id != target_id', name='ck_links_no_self_ref'),
    sa.ForeignKeyConstraint(['source_id'], ['ontology_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['ontology_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['ontology_link_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_id', 'source_id', 'target_id', name='uq_links_type_source_target')
    )
    op.create_index('idx_links_source', 'ontology_links', ['source_id'], unique=False)
    op.create_index('idx_links_target', 'ontology_links', ['target_id'], unique=False)
    op.create_index('idx_links_user_type', 'ontology_links', ['user_id', 'type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_links_user_type', table_name='ontology_links')
    op.drop_index('idx_links_target', table_name='ontology_links')
    op.drop_index('idx_links_source', table_name='ontology_links')
    op.drop_table('ontology_links')
    op.drop_index('idx_onto_action_logs_user', table_name='ontology_action_logs')
    op.drop_index('idx_onto_action_logs_type', table_name='ontology_action_logs')
    op.drop_table('ontology_action_logs')
    op.drop_index('idx_objects_user_type', table_name='ontology_objects')
    op.drop_index('idx_objects_user_status', table_name='ontology_objects')
    op.drop_index('idx_objects_source', table_name='ontology_objects')
    op.drop_index('idx_objects_embedding', table_name='ontology_objects', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('ontology_objects')
    op.drop_index('idx_link_types_user', table_name='ontology_link_types')
    op.drop_table('ontology_link_types')
    op.drop_index('idx_action_types_user', table_name='ontology_action_types')
    op.drop_table('ontology_action_types')
    op.drop_index('idx_object_types_user', table_name='ontology_object_types')
    op.drop_index('idx_object_types_embedding', table_name='ontology_object_types', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('ontology_object_types')
    # ### end Alembic commands ###
