"""add habits and habit_logs tables

Revision ID: 2621639f0b73
Revises: 5061daedeb1e
Create Date: 2026-03-21 22:12:21.921144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2621639f0b73'
down_revision: Union[str, Sequence[str], None] = '5061daedeb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency_type', sa.String(), nullable=False),
    sa.Column('frequency_value', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('target_unit', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("frequency_type IN ('daily','specific_days','times_per_week','every_n_days')", name='ck_habits_frequency_type'),
    sa.CheckConstraint("status IN ('active','paused','archived')", name='ck_habits_status'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_habits_user', 'habits', ['user_id', 'status'], unique=False)
    op.create_table('habit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('ui','chat')", name='ck_habit_logs_source'),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'log_date', name='uq_habit_log_date')
    )
    op.create_index('idx_habit_logs_habit_date', 'habit_logs', ['habit_id', 'log_date'], unique=False)
    op.create_index('idx_habit_logs_user_date', 'habit_logs', ['user_id', 'log_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_habit_logs_user_date', table_name='habit_logs')
    op.drop_index('idx_habit_logs_habit_date', table_name='habit_logs')
    op.drop_table('habit_logs')
    op.drop_index('idx_habits_user', table_name='habits')
    op.drop_table('habits')
    # ### end Alembic commands ###
