"""add ontology automations tables

Revision ID: 4578261c8eda
Revises: b4c49d5a46a8
Create Date: 2026-03-28 16:19:26.774473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4578261c8eda'
down_revision: Union[str, Sequence[str], None] = 'b4c49d5a46a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontology_automations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('insight_type', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('auto_execute', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_type IN ('create_link','create_node','notification','suggest')", name='ck_ont_automations_action_type'),
    sa.CheckConstraint("insight_type IN ('hub_node','isolated','strong_path','conflict','opportunity','trend')", name='ck_ont_automations_insight_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ont_automations_user', 'ontology_automations', ['user_id'], unique=False)
    op.create_table('ontology_automation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('automation_id', sa.UUID(), nullable=False),
    sa.Column('insight_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success','failed','pending_approval')", name='ck_ont_auto_logs_status'),
    sa.ForeignKeyConstraint(['automation_id'], ['ontology_automations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insight_id'], ['ontology_insights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ont_auto_logs_user', 'ontology_automation_logs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ont_auto_logs_user', table_name='ontology_automation_logs')
    op.drop_table('ontology_automation_logs')
    op.drop_index('idx_ont_automations_user', table_name='ontology_automations')
    op.drop_table('ontology_automations')
    # ### end Alembic commands ###
