"""add retrospectives insights tables

Revision ID: 5061daedeb1e
Revises: ec918b090ca4
Create Date: 2026-03-20 13:33:45.356087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5061daedeb1e'
down_revision: Union[str, Sequence[str], None] = 'ec918b090ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retrospectives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('challenges', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('goals_progress', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('conversation_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("period_type = 'weekly'", name='ck_retro_period_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_type', 'period_start', name='uq_retro_period')
    )
    op.create_index('idx_retro_user', 'retrospectives', ['user_id', 'period_end'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('retrospective_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('source_period', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('topic_trend','goal_pattern','activity_pattern','recommendation')", name='ck_insight_category'),
    sa.ForeignKeyConstraint(['retrospective_id'], ['retrospectives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_insights_retro', 'insights', ['retrospective_id'], unique=False)
    op.create_index('idx_insights_user', 'insights', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_insights_user', table_name='insights')
    op.drop_index('idx_insights_retro', table_name='insights')
    op.drop_table('insights')
    op.drop_index('idx_retro_user', table_name='retrospectives')
    op.drop_table('retrospectives')
    # ### end Alembic commands ###
