"""add ontology_import_sources table

Revision ID: 62b7267b1f7c
Revises: 4578261c8eda
Create Date: 2026-03-29 15:33:46.985562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b7267b1f7c'
down_revision: Union[str, Sequence[str], None] = '4578261c8eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontology_import_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_imported_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('markdown','db_goals','db_habits','db_memories','db_messages')", name='ck_import_sources_type'),
    sa.CheckConstraint("status IN ('imported','outdated','deleted')", name='ck_import_sources_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_path', name='uq_import_sources_user_path')
    )
    op.create_index('idx_import_sources_user', 'ontology_import_sources', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_import_sources_user', table_name='ontology_import_sources')
    op.drop_table('ontology_import_sources')
    # ### end Alembic commands ###
