"""add ontology_insights table

Revision ID: b4c49d5a46a8
Revises: 254675b4ef60
Create Date: 2026-03-28 13:53:03.060829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4c49d5a46a8'
down_revision: Union[str, Sequence[str], None] = '254675b4ef60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontology_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('actionable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('action_suggestion', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("insight_type IN ('hub_node','isolated','strong_path','conflict','opportunity','trend')", name='ck_insights_type'),
    sa.CheckConstraint("status IN ('new','read','acted','dismissed')", name='ck_insights_status'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_insights_confidence'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_insights_user_status', 'ontology_insights', ['user_id', 'status'], unique=False)
    op.create_index('idx_insights_user_type', 'ontology_insights', ['user_id', 'insight_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_insights_user_type', table_name='ontology_insights')
    op.drop_index('idx_insights_user_status', table_name='ontology_insights')
    op.drop_table('ontology_insights')
    # ### end Alembic commands ###
