"""add calendar_event_id to habits

Revision ID: c4661064b1bc
Revises: 2621639f0b73
Create Date: 2026-03-23 14:31:57.822841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4661064b1bc'
down_revision: Union[str, Sequence[str], None] = '2621639f0b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('calendar_event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'calendar_event_id')
    # ### end Alembic commands ###
