"""add events table

Revision ID: c69e6a4fae5e
Revises: 80f539b47509
Create Date: 2026-03-24 00:18:53.137081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c69e6a4fae5e'
down_revision: Union[str, Sequence[str], None] = '80f539b47509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_aggregate', 'events', ['aggregate_id', 'created_at'], unique=False)
    op.create_index('idx_events_type', 'events', ['event_type', 'created_at'], unique=False)
    op.create_index('idx_events_user', 'events', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_user', table_name='events')
    op.drop_index('idx_events_type', table_name='events')
    op.drop_index('idx_events_aggregate', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
